# 名称
name: taiyiflow-docs

# 描述
description: 太乙智启官方文档站

# 镜像编译参数
docker:
  # 镜像名称
  image: snz1.cn/taiyiflow/docs
  # 镜像编译文件(默认：Dockerfile)
  file: Dockerfile
  # 目标平台
  platform:
    - linux/amd64
    - linux/arm64

# 服务定义
service:
  # 端口定义
  ports:
    - 5002:80

  # 环境变量
  envs:
    - WEB_CONTEXT_PATH=/taiyi/docs
    - TZ=Asia/Shanghai

  # 心跳检查
  healthcheck:
    url: /health
    interval: 10s
    timeout: 10s
    period: 30s
    retries: 30

  # 路由定义
  ingress:
    - backend-port: 80
      strip-path: true
      anonymous:
        - /taiyi/docs
